controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    front_left_joint_pid: {p: 8.2,  i: 0.041, d: 0.00034}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50