controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    front_left_joint_pid: {p: 41000,  i: 410, d: 61}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50