controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    front_left_joint_pid: { p: 41000,  i: 410, d: 61, antiwindup: true }
    front_right_joint_pid: { p: 41000,  i: 410, d: 61, antiwindup: true }
    back_left_joint_pid: { p: 41000,  i: 410, d: 61, antiwindup: true }
    back_right_joint_pid: { p: 41000,  i: 410, d: 61, antiwindup: true }
    wheel_radius: 0.07625
    wheel_track: 0.4
    wheel_base: 0.4
    use_global_vel: false
    chassis_acceleration: 5.0

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50